steps:
  - name: gcr.io/cloud-builders/gcloud
    id: "access-backend-url-secret"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Fetching secret..."
        BACKEND_URL=$(gcloud secrets versions access latest --secret=NEXT_PUBLIC_BACKEND_URL)
        echo "BACKEND_URL=$BACKEND_URL" > backend.env

  - name: gcr.io/cloud-builders/docker
    id: "build-frontend"
    env:
      - $(cat backend.env)
    args:
      [
        "build",
        "-f",
        "Dockerfile.prod",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/snake-frontend-repo/snake-frontend",
        "--build-arg",
        "NEXT_PUBLIC_BACKEND_URL=$BACKEND_URL",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args: [
      "push",
      "us-central1-docker.pkg.dev/$PROJECT_ID/snake-frontend-repo/snake-frontend"
    ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "snake-frontend",
        "--image",
        "us-central1-docker.pkg.dev/$PROJECT_ID/snake-frontend-repo/snake-frontend",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--set-env-vars",
        "NEXT_PUBLIC_BACKEND_URL=$(gcloud secrets versions access latest --secret=NEXT_PUBLIC_BACKEND_URL)"
      ]
