steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/menuflashjdvpl/snake-frontend-repo/snake-frontend',
        '-f',
        'dockerfile.prod',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/menuflashjdvpl/snake-frontend-repo/snake-frontend',
      ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'snake-frontend',
        '--image', 'us-central1-docker.pkg.dev/menuflashjdvpl/snake-frontend-repo/snake-frontend',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
